name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: kivy/buildozer:2022.05.20

    steps:
    - uses: actions/checkout@v4

    - name: Build APK
      run: |
        apt-get update && apt-get install -y git wget unzip
        wget https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
        unzip android-ndk-r13b-linux-x86_64.zip
        export ANDROID_NDK_HOME=/github/workspace/android-ndk-r13b
        export ANDROID_HOME=/opt/android/android-sdk
        export PATH=$PATH:$ANDROID_NDK_HOME
        buildozer android debug
      env:
        BUILDOZER_WARN_ON_ROOT: 0

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: habit-tracker-debug
        path: bin/*.apk
        retention-days: 5
